[package]
name = "aoc-2021"
version = "0.1.0"
edition = "2021"
authors = ["Jorge Gallegos <kad@blegh.net>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
